from dataclasses import dataclass
from pathlib import Path


@dataclass
class Module:
    script: str      # module-isi.sh
    label: str       # for builder prompt only
    name: str        # short name in logs
    func_name: str   # bash function name of embedded module
    status_flag: str # name of status_flag() helper in main.sh (not used by builder)


MODULES = [
    Module(
        "module-a5e.sh",
        "A5E                (Cubie headless + initbox)",
        "A5E",
        "module_a5e",
        "has_a5e",
    ),
        
    Module(
        "module-isi.sh",
        "ISI                (ISI simulator 3 clients)",
        "ISI",
        "module_isi",
        "has_isi",
    ),
    Module(
        "module-fms.sh",
        "FMS                (CAN/FMS simulator)",
        "FMS",
        "module_fms",
        "has_fms",
    ),
    Module(
        "module-hotspot.sh",
        "Hotspot            (wlan0 AP for SSH)",
        "Hotspot",
        "module_hotspot",
        "has_hotspot",
    ),
    Module(
        "module-dashboard.sh",
        "Dashboard          (Node-RED + ttyd portal)",
        "Dashboard",
        "module_dashboard",
        "has_dashboard",
    ),
    Module(
        "module-ws-br0.sh",
        "Wireshark + Bridge (capture on br0)",
        "Wireshark + Bridge",
        "module_ws_br0",
        "has_wireshark",
    ),
    Module(
        "module-rtc.sh",
        "RTCsync            (rtc-sync timer + service)",
        "RTCsync",
        "module_rtc",
        "has_rtcsync",
    ),
]


def prompt_selection(modules: list[Module]) -> list[Module]:
    print("Initbox interactive builder")
    print("---------------------------")
    print("Which modules do you want to EMBED into the single-file installer?")
    print()
    for idx, m in enumerate(modules, start=1):
        print(f"  {idx}) {m.label}   [file: {m.script}]")
    print()
    print("You can enter:")
    print("  - 'a' to include ALL modules")
    print("  - a comma-separated list of numbers, e.g. 1,3,5")
    print()

    while True:
        choice = input("Modules to include [a = all]: ").strip()
        if choice == "" or choice.lower() == "a":
            return list(modules)

        parts = [p.strip() for p in choice.split(",") if p.strip()]
        idxs: list[int] = []
        bad = False

        for p in parts:
            if not p.isdigit():
                print(f"Invalid entry: {p!r}. Use numbers like 1,3,5 or 'a'.")
                bad = True
                break
            i = int(p)
            if i < 1 or i > len(modules):
                print(f"Index out of range: {i}. Valid range is 1..{len(modules)}.")
                bad = True
                break
            idxs.append(i - 1)

        if bad:
            continue

        seen = set()
        selected: list[Module] = []
        for i in idxs:
            if i not in seen:
                seen.add(i)
                selected.append(modules[i])

        if not selected:
            print("No modules selected, defaulting to all.")
            return list(modules)

        print()
        print("You selected to EMBED:")
        for m in selected:
            print(f"  - {m.label} ({m.script})")
        confirm = input("Proceed with these modules? [Y/n]: ").strip().lower()
        if confirm in ("", "y", "yes"):
            return selected

        print("Okay, let's choose again.")
        print()


def build_modules_block(base: Path, selected: list[Module]) -> str:
    """Embed the selected module-*.sh scripts as bash functions using heredocs."""
    lines: list[str] = []
    lines.append("# ------------ Embedded modules (autogenerated) ------------")
    for mod in selected:
        mod_path = base / mod.script
        if not mod_path.exists():
            raise SystemExit(f"ERROR: Missing module script: {mod_path}")

        mod_text = mod_path.read_text(encoding="utf-8")

        delim = f"__{mod.script.replace('.', '_').upper()}__EOT__"
        if delim in mod_text:
            raise SystemExit(
                f"ERROR: Delimiter {delim!r} appears inside {mod.script}, adjust builder."
            )

        lines.append("")
        lines.append(f"{mod.func_name}() {{")
        lines.append(f"bash -s <<'{delim}'")
        lines.append(mod_text.rstrip("\n"))
        lines.append(delim)
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def build_run_module_block(selected: list[Module]) -> str:
    """Create run_module() that dispatches to embedded module_* functions.

    NOTE: We do NOT touch the menu in main.sh anymore.
    If a menu entry calls a module that was not embedded,
    we print a clear message.
    """
    lines: list[str] = []
    lines.append("# ------------ Module dispatcher (autogenerated) ------------")
    lines.append("run_module() {")
    lines.append('  # usage: run_module module-*.sh \"Pretty Name\"')
    lines.append("  local script=\"$1\"")
    lines.append("  local name=\"$2\"")
    lines.append("")
    lines.append("  echo")
    lines.append("  echo \"=== Running module: ${name} (${script}) ===\"")
    lines.append("  local rc=0")
    lines.append("")
    lines.append("  case \"$script\" in")

    for mod in selected:
        lines.append(f"    '{mod.script}')")
        lines.append(f"      {mod.func_name} || rc=$?")
        lines.append("      ;;")

    lines.append("    *)")
    lines.append('      echo \"Module ${name} (${script}) is NOT embedded in this installer.\"')
    lines.append('      echo \"This installer was built without that module.\"')
    lines.append("      rc=1")
    lines.append("      ;;")
    lines.append("  esac")
    lines.append("")
    lines.append("  echo \"=== Module ${name} finished with exit code ${rc} ===\"")
    lines.append("")
    lines.append("  echo")
    lines.append('  read -rp \"Press ENTER to return to menu...\" _')
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def merge_main(main_text: str, modules_block: str, run_block: str) -> str:
    """Splice embedded modules + dispatcher into main.sh, without touching the menu."""

    disp_marker = "# ------------ Module dispatcher"
    hdr_marker = "# ------------ Logging header"

    disp_start = main_text.find(disp_marker)
    if disp_start == -1:
        raise SystemExit("ERROR: Could not find module dispatcher marker in main.sh")

    hdr_idx = main_text.find(hdr_marker, disp_start)
    if hdr_idx == -1:
        raise SystemExit("ERROR: Could not find logging header marker in main.sh")

    # Everything BEFORE the dispatcher comment stays as-is
    part_a = main_text[:disp_start]

    # Our new embedded modules + run_module(), then continue from logging header onward
    part_b = (
        modules_block.rstrip("\n")
        + "\n\n"
        + run_block.rstrip("\n")
        + "\n\n"
        + main_text[hdr_idx:]
    )

    return part_a + part_b


def build_installer() -> None:
    base = Path(__file__).resolve().parent
    main_path = base / "main.sh"
    if not main_path.exists():
        raise SystemExit(f"ERROR: main.sh not found in {base}")

    main_text = main_path.read_text(encoding="utf-8")

    selected = prompt_selection(MODULES)
    modules_block = build_modules_block(base, selected)
    run_block = build_run_module_block(selected)

    combined = merge_main(main_text, modules_block, run_block)

    out_path = base / "cubie-installer.sh"
    out_path.write_text(combined, encoding="utf-8")

    # chmod +x
    mode = out_path.stat().st_mode
    out_path.chmod(mode | 0o111)

    print()
    print(f"Wrote installer to: {out_path}")
    print("You can now run it with: sudo ./cubie-installer.sh")


if __name__ == "__main__":
    build_installer()
